In [3]:
pip install tensorflow_text

     |████████████████████████████████| 4.9 MB 13.9 MB/s 


In [4]:
import tensorflow_hub as hub
import tensorflow_text as text

In [9]:
preprocess_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
encoder_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'

In [10]:
# pre process layer
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [11]:
text_test = ['nice movie indeed', 'I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [12]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [13]:
bert_model = hub.KerasLayer(encoder_url)
bert_results = bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['sequence_output', 'default', 'encoder_outputs', 'pooled_output'])

In [14]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.79177403, -0.21411917,  0.49769512, ...,  0.24465209,
        -0.47334483,  0.81758696],
       [-0.9171231 , -0.4793518 , -0.7865696 , ..., -0.6175173 ,
        -0.7102685 ,  0.92184293]], dtype=float32)>

In [19]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292039,  0.08567829,  0.14476822, ..., -0.09677094,
          0.08722122,  0.07711113],
        [ 0.17839348, -0.19006087,  0.5034941 , ..., -0.0586984 ,
          0.32717144, -0.15578577],
        [ 0.18701448, -0.4338879 , -0.4887518 , ..., -0.15502778,
          0.00145195, -0.24470937],
        ...,
        [ 0.12083066,  0.12884228,  0.46453536, ...,  0.0737552 ,
          0.1744199 ,  0.16522072],
        [ 0.07967893, -0.01190648,  0.50225407, ...,  0.13777722,
          0.21002227,  0.00624616],
        [-0.0721269 , -0.2830346 ,  0.59033346, ...,  0.4755192 ,
          0.16668513, -0.08920337]],

       [[-0.07900593,  0.3633515 , -0.2110156 , ..., -0.17183776,
          0.1629975 ,  0.6724269 ],
        [ 0.27883485,  0.43716323, -0.35764667, ..., -0.04463657,
          0.38315177,  0.58879846],
        [ 1.2037673 ,  1.072702  ,  0.48408806, ...,  0.24920997,
          0.40730938,  0.40481803],
        ...,